### ISSUE TITLE
Video on 10/10?

### ISSUE THREAD

**Issue by nathan-collins** [USQ-Media-Services/animated-screening-project#111]
Find out what the expected result should be when a person is on 10/10 videos

**Comment by nathan-collins** [comment]
This will need to remove all local storage items so the app starts again from scratch if needed.

**Comment by nathan-collins** [comment]
What happens if a browser is closed half way through and another person open the same browser?

**Comment by nathan-collins** [comment]
Sent email with these questions that need to be answered

**Comment by lynchz** [comment]
I will find out from the client what they expect to happen to all #111 related questions you’ve sent through ☺

**Comment by nathan-collins** [comment]
A small part of this has been committed to the home page, I was going to reuse that page because it is identical to designs.

properties:
   ```
 isFinished: {
      type: Boolean,
      value: false
    },

    buttonText: {
      type: String,
      value: 'Start'
    }
```

have been added for this work
